In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/cleaned_churn.csv")

df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total eve minutes,Total eve calls,Total night minutes,Total night calls,Total intl minutes,Total intl calls,Customer service calls,Churn,Estimated Revenue
0,KS,128,415,0,1,25,265.1,110,197.4,99,244.7,91,10.0,3,1,0,75.5575
1,OH,107,415,0,1,26,161.6,123,195.5,103,254.4,103,13.7,3,1,0,59.2365
2,NJ,137,415,0,0,0,243.4,114,121.2,110,162.6,104,12.2,5,0,0,62.2910
3,OH,84,408,1,0,0,299.4,71,61.9,88,196.9,89,6.6,7,2,0,66.8020
4,OK,75,415,1,0,0,166.7,113,148.3,122,186.9,121,10.1,3,3,0,52.0820

In [2]:
df = df.reset_index(drop=True)
df['customer_id'] = df.index + 1

In [3]:
df[['customer_id']].head()

   customer_id
0            1
1            2
2            3
3            4
4            5

In [4]:
customers = df[['customer_id', 'State', 'Account length', 'Churn']].copy()
customers.columns = ['customer_id', 'state', 'account_length', 'churn']

In [5]:
subscriptions = df[['customer_id', 'International plan', 'Voice mail plan']].copy()
subscriptions.columns = ['customer_id', 'international_plan', 'voice_mail_plan']

In [6]:
usage_metrics = df[[
    'customer_id',
    'Total day minutes', 'Total eve minutes',
    'Total night minutes', 'Total intl minutes',
    'Total day calls', 'Total eve calls',
    'Total night calls', 'Total intl calls'
]].copy()

usage_metrics.columns = [
    'customer_id',
    'day_minutes', 'eve_minutes',
    'night_minutes', 'intl_minutes',
    'day_calls', 'eve_calls',
    'night_calls', 'intl_calls'
]

In [7]:
support_metrics = df[['customer_id', 'Customer service calls']].copy()
support_metrics.columns = ['customer_id', 'customer_service_calls']

In [8]:
df['estimated_revenue'] = (
    df['Total day minutes'] * 0.17 +
    df['Total eve minutes'] * 0.085 +
    df['Total night minutes'] * 0.045 +
    df['Total intl minutes'] * 0.27
)

revenue_summary = df[['customer_id', 'estimated_revenue']].copy()

revenue_summary['revenue_risk_flag'] = np.where(
    df['Churn'] == 1,
    'At Risk',
    'Stable'
)

In [9]:
customers.to_csv("../data/relational/customers.csv", index=False)
subscriptions.to_csv("../data/relational/subscriptions.csv", index=False)
usage_metrics.to_csv("../data/relational/usage_metrics.csv", index=False)
support_metrics.to_csv("../data/relational/support_metrics.csv", index=False)
revenue_summary.to_csv("../data/relational/revenue_summary.csv", index=False)